language: haskell

ghc:
  - 7.6.3
  - 7.8.4

install:
  - cabal update
  - cabal install -j --only-dependencies

script:
  - cabal configure
  - cabal build
  - cabal install
  - ( cd examples ; runhaskell Examples.hs )
